### ISSUE TITLE
slovenska verzia

### ISSUE THREAD

**Issue by granci** [jkremser/nahodny-slusny-cech#1]
ahoj, nemam moc skusenosti s githubom, neviem ako ta tu nejak normalne kontaktovat... chcem ti len dat na vedomie, ze som som si to forkol a spravil SK verziu: https://slusny-slovien.herokuapp.com/
ak s tym nesuhlasis, daj vediet a zostrelim to...

**Comment by jkremser** [comment]
:+1:
Nech tam ale ten zdroj
