### ISSUE TITLE
Chybí "vítači" a "zelený mozky"

### ISSUE THREAD

**Issue by jachymb** [jkremser/nahodny-slusny-cech#3]
v seznamu bad guys nebo jinde.

**Comment by ok1xoe** [comment]
Jeste tam chybi černoprdelníci, Bělobrádek, Jurečka a nějaké nadávka na církevní restituce

**Comment by jkremser** [comment]
neco malo jsem zas pridal tady https://github.com/Jiri-Kremser/nahodny-slusny-cech/commit/38a28bacca73aecbe6e5818cd8b27e3e8da066ed
